
##No hits
hist(log1p(Alaska$UHDICM))
str(Alaska[which(Alaska$UHDICM<0),])
str(Alaska[which(Alaska$LHDICM>800),])
str(Alaska[which(Alaska$UHDICM>800),])
str(Alaska[which(Alaska$PHIKCL>=9.5),])
str(Alaska[which(Alaska$PHIHOX>=10.5),])
str(Alaska[which(Alaska$CRFVOL>100),])
str(Alaska[which(Alaska$SNDPPT>100),])
str(Alaska[which(Alaska$SNDPPT<0),])
str(Alaska[which(Alaska$SLTPPT>100),])
str(Alaska[which(Alaska$SLTPPT<0),])
str(Alaska[which(Alaska$CLYPPT>100),])
str(Alaska[which(Alaska$CLYPPT<0),])
str(Alaska[which(Alaska$BLD==0),])
str(Alaska[which(Alaska$BLD<0),])
str(Alaska[which(Alaska$PHIHOX<2),])
str(Alaska[which(Alaska$ORCDRC>=600),])
str(Alaska[which(Alaska$CECSUM>=300),])